"""Your migration message here

Revision ID: 1ec7464391c0
Revises: 59d8fc15434b
Create Date: 2024-09-05 09:54:50.185112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1ec7464391c0'
down_revision = '59d8fc15434b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_info', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('box_num',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_info', schema=None) as batch_op:
        batch_op.alter_column('box_num',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
