"""init lotInfo  table

Revision ID: 59d8fc15434b
Revises: 999b08fc48ff
Create Date: 2024-09-05 09:37:50.047699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59d8fc15434b'
down_revision = '999b08fc48ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', mysql.JSON(), nullable=False),
    sa.Column('productionPlan_num', sa.Integer(), nullable=False),
    sa.Column('supply_num', sa.Integer(), nullable=False),
    sa.Column('box_num', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot_info')
    # ### end Alembic commands ###
