"""Added BoxNum table and relationship to LotInfo

Revision ID: 5dca12306ad7
Revises: 1ec7464391c0
Create Date: 2024-09-17 09:43:04.486941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dca12306ad7'
down_revision = '1ec7464391c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_num',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('lot_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_info_id'], ['lot_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_info', schema=None) as batch_op:
        batch_op.drop_column('box_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_num', sa.VARCHAR(), nullable=False))

    op.drop_table('box_num')
    # ### end Alembic commands ###
