"""add user model

Revision ID: 999b08fc48ff
Revises: afd0c6562762
Create Date: 2024-08-12 13:22:44.699448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999b08fc48ff'
down_revision = 'afd0c6562762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
