"""init machine table

Revision ID: afd0c6562762
Revises: 
Create Date: 2024-07-30 15:59:26.484751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd0c6562762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=40), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('good_num', sa.Integer(), nullable=False),
    sa.Column('ng_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_info')
    # ### end Alembic commands ###
